# Default configuration for the application

# Environment specific settings (development, staging, production)
environment: development

# Services configuration
services:
  # Redis cache service
  redis:
    enabled: true
    variant: default
    connectionString: ${REDIS_CONNECTION_STRING:-redis://localhost:6379}

  # PostgreSQL database service
  postgres:
    enabled: true
    variant: default
    connectionString: ${POSTGRES_CONNECTION_STRING:-postgresql://user:password@localhost:5432/mydb}

  # Azure Cosmos DB service
  cosmos:
    enabled: false
    variant: default
    endpoint: ${COSMOS_ENDPOINT:-https://localhost:8081}
    key: ${COSMOS_KEY:-your-key-here}
    database: ${COSMOS_DATABASE:-mydb}

  # Blob storage service
  blob:
    enabled: false
    variant: default
    connectionString: ${BLOB_CONNECTION_STRING:-DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;}
    container: ${BLOB_CONTAINER:-default}

  # Web PubSub service
  webpubsub:
    enabled: false
    variant: default
    connectionString: ${WEBPUBSUB_CONNECTION_STRING:-Endpoint=https://example.webpubsub.azure.com;AccessKey=your-access-key;Version=1.0;}
    hub: ${WEBPUBSUB_HUB:-default}

# Feature flags
features:
  enableAnalytics: false
  enableCaching: true
  enableLogging: true

# Application settings
app:
  port: 3000
  logLevel: info
  environment: ${NODE_ENV:-development}
  instanceId: ${HOSTNAME:-local}
